name: "Test and coverage check"
description: "Test and coverage check with gcovr, pass if coverage is greater than 20%"

runs:
  using: "composite"
  steps:
    - name: "Run coverage"
      shell: bash
      run: |
        PROJECT_PATH=$(pwd)

<<<<<<< HEAD
        # ToDo: run tests and show failed tests in such case
        ctest --test-dir build/tests --output-on-failure

        # ToDo: run coverage tests and save output file
=======
        # ToDo: Add documentation and describe better this command
        ctest --test-dir build/tests --output-on-failure

        # ToDo: Add documentation and describe better this command
>>>>>>> cd7a83c (CL:)


        gcovr -r $PROJECT_PATH . > $PROJECT_PATH/coverage.txt

        echo "Runnig: gcovr -r $PROJECT_PATH ."

        cat $PROJECT_PATH/coverage.txt

        # Find the value of correct coverage
<<<<<<< HEAD
        # ToDo: show results
=======
        # ToDo: Add documentation and describe better this command
>>>>>>> cd7a83c (CL:)
        COVERAGE_RESULT=$(grep "TOTAL" $PROJECT_PATH/coverage.txt | awk '{print $NF}' | cut -d '%' -f 1)

        # Coverage lines GT 20
        if [ "$(echo "$COVERAGE_RESULT > 20" | bc)" -eq 1 ]; then
            echo "Coverage is greater than 20%. Nice!"
            exit 0
        else
            echo "Error: Coverage is less than or equal to 20%"
            exit 1
        fi

    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Tests or coverage errors!!!
        path: $(pwd)/error_flag.txt
        retention-days: 1
